name = "tuim-bug-report"
main = "src/index.ts"
compatibility_date = "2026-07-15"
workers_dev = true
preview_urls = false

[vars]
GITHUB_OWNER = "Rouboufy"
GITHUB_REPO = "tuim"

[[kv_namespaces]]
binding = "REPORT_LIMITS"
id = "83a8939a558245bf81ac780051d1313a"
